[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "123"

[auth.google]
client_id = "SEU_CLIENT_ID"
client_secret = "SEU_CLIENT_SECRET"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
